### ISSUE TITLE
三叶可以做一下竞赛系列吗

### ISSUE THREAD

**Issue by alittlebitcool** [SharingSource/LogicStack-LeetCode#49]
三叶可以做一下周赛系列吗？可以从83场周赛开始 ，或者从最新一场的周赛开始。想看！

**Comment by SharingSource** [comment]
我确实写过呢，周赛和双周赛都写过。

不过当时还没开始写每日一题题解，公众号也没开始什么系列题解，时间还算匀得过来。

其中有两次比赛还整理出来放到公众号了：

双周赛：https://mp.weixin.qq.com/s?__biz=MzU4NDE3MTEyMA==&mid=2247484229&idx=1&sn=3cff7c795a89211e28566247bfa1c1f0

周赛：https://mp.weixin.qq.com/s?__biz=Mzg5ODU2NjIyMw==&mid=2247484696&idx=2&sn=de23152975e5a2a0c7c6286f3a57e93f

之所以没有继续，是因为周赛题解是一个「时效性很强」的内容，通常需要比赛结束后 2 小时内全部写出来会比较有意义，如果隔的时间长的话，意义就不大了（指大多数需要搞懂的读者都搞懂了）。

因此如果我在维持更新「每日一题」的前提下写周赛题解的话，那么比赛当天我需要写四篇题解（不算 t1），几乎会占掉我一天的时间。

加之我公众号现在落下的、还没完结的系列还比较多，所以目前还没有拓展到周赛题解。

但我确实是希望能够在下半年，把手上未完结的题解解决一下，然后开始参与到周赛当中，当然也包括输出周赛题解。

anyway，敬请期待吧，一定会来的 ~
